# Generated by Django 6.0.6 on 2026-06-14 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(help_text='Porcentaje, Fijo', max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('esta_activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'promociones',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_cobro', models.CharField(help_text='Por Kg, Por Prenda', max_length=50)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('anticipo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado_pago', models.CharField(default='Pendiente', help_text='Pendiente, Parcial, Liquidado', max_length=50)),
                ('estado_actual', models.CharField(default='Recibida', help_text='Recibida, Clasificada, En lavado, En secado, En planchado, Empaquetada, Lista para entrega, Entregada', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='lavanderia.cliente')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'db_table': 'ordenes',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(help_text='Efectivo, Transferencia, Tarjeta', max_length=50)),
                ('tipo_pago', models.CharField(help_text='Anticipo, Saldo Final', max_length=50)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='lavanderia.orden')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoLavado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(help_text='Recibida, Clasificada, En lavado, En secado, En planchado, Empaquetada, Lista para entrega, Entregada', max_length=50)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='lavanderia.orden')),
            ],
            options={
                'verbose_name': 'Seguimiento de Lavado',
                'verbose_name_plural': 'Seguimientos de Lavado',
                'db_table': 'seguimiento_lavado',
            },
        ),
        migrations.CreateModel(
            name='PrendaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prenda', models.CharField(help_text='Camisa, Pantalón, Toalla, Sábana, etc.', max_length=100)),
                ('cantidad', models.IntegerField(default=1)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en Kg', max_digits=5, null=True)),
                ('es_delicada', models.BooleanField(default=False)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prendas', to='lavanderia.orden')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lavanderia.servicio')),
            ],
            options={
                'verbose_name': 'Prenda de Orden',
                'verbose_name_plural': 'Prendas de Orden',
                'db_table': 'prendas_orden',
            },
        ),
    ]
