# Generated by Django 6.0.6 on 2026-06-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavanderia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prendaorden',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario o tarifa por kg aplicada', max_digits=10, null=True),
        ),
    ]
