# Generated by Django 6.0.6 on 2026-06-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavanderia', '0002_prendaorden_precio_unitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='LavaFácil', max_length=150)),
                ('telefono_contacto', models.CharField(blank=True, default='+1 234 567 8900', max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, default='Av. Principal 123, Ciudad', null=True)),
                ('correo', models.EmailField(blank=True, default='contacto@lavafacil.com', max_length=100, null=True)),
                ('simbolo_moneda', models.CharField(default='$', help_text='Símbolo a mostrar en la interfaz (ej. $, S/, €)', max_length=10)),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de IVA/IGV (ej. 16.00)', max_digits=5)),
                ('mensaje_ticket_cabecera', models.TextField(blank=True, default='RFC: XXXXXX000000\n¡Bienvenido!', null=True)),
                ('mensaje_ticket_pie', models.TextField(blank=True, default='¡Gracias por su preferencia!\nLas prendas no reclamadas después de 30 días causarán recargo de almacenaje o serán donadas.', null=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
                'db_table': 'configuracion',
            },
        ),
    ]
