# Generated by Django 6.0.6 on 2026-06-30 18:48

from django.db import migrations


def split_names(apps, schema_editor):
    Cliente = apps.get_model('lavanderia', 'Cliente')
    for cliente in Cliente.objects.all():
        full_name = cliente.nombre.strip()
        parts = full_name.split()
        if len(parts) >= 4:
            cliente.nombre = " ".join(parts[:-2])
            cliente.apellido = " ".join(parts[-2:])
        elif len(parts) == 3:
            cliente.nombre = parts[0]
            cliente.apellido = " ".join(parts[1:])
        elif len(parts) == 2:
            cliente.nombre = parts[0]
            cliente.apellido = parts[1]
        else:
            cliente.nombre = full_name
            cliente.apellido = ""
        cliente.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lavanderia', '0005_cliente_apellido_cliente_cedula_alter_cliente_nombre'),
    ]

    operations = [
        migrations.RunPython(split_names),
    ]
