# Generated by Django 6.0.6 on 2026-06-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavanderia', '0006_auto_20260630_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Prenda de Catálogo',
                'verbose_name_plural': 'Prendas de Catálogo',
                'db_table': 'catalogo_prendas',
            },
        ),
    ]
