# Generated by Django 6.0.6 on 2026-06-30 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavanderia', '0008_populate_catalogo_prendas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='lavanderia.promocion'),
        ),
    ]
