# Generated by Django 6.0.7 on 2026-07-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavanderia', '0010_registroauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='color_tema',
            field=models.CharField(default='#2174ea', help_text='Color principal del sistema en Hexadecimal (ej. #2174ea)', max_length=20),
        ),
    ]
