# Generated by Django 6.0.7 on 2026-07-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lavanderia', '0011_configuracion_color_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='color_secundario',
            field=models.CharField(default='#0f172a', help_text='Color secundario/barra lateral en Hexadecimal (ej. #0f172a)', max_length=20),
        ),
    ]
